version: '3.8'
services:
  badge-service:
    build: .
    container_name: microservice_badge
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - kafka
    environment:
      - SPRING_PROFILES_ACTIVE=default
    networks:
      - melodyme-net

  mongodb:
    image: mongo:latest
    container_name: db_M_badge
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: db_badge
    ports:
      - "27017:27017"
    volumes:
      - pgdataMongo:/data/db
    networks:
      - melodyme-net

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper_M_badge
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - melodyme-net

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka_M_badge
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - melodyme-net

volumes:
  pgdataMongo:

networks:
  melodyme-net:
