version: '3.8'
services:
  badge-service:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - SPRING_PROFILES_ACTIVE=default
    networks:
      - melodyme-net
  mongodb:
    image: mongo:latest
    container_name: db_badge
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: db_badge
    ports:
      - "27017:27017"
    volumes:
      - pgdataMongo:/var/lib/mongodb/data

volumes:
  pgdataMongo: