name: CI - Gestion des Badges

on:
  push:
    branches:
      - develop
      - feature/*
  pull_request:
    branches:
      - develop

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Run Maven lint (Checkstyle)
        run: mvn checkstyle:check

  test:
    name: Build and Test
    runs-on: ubuntu-latest
    needs: lint

    services:
      mongodb:
        image: mongo:latest
        env:
          MONGO_INITDB_ROOT_USERNAME: mongo
          MONGO_INITDB_ROOT_PASSWORD: root
          MONGO_INITDB_DATABASE: db_badge
        ports:
          - 27017:27017
        options: >-
          --health-cmd "echo 'db.runCommand({ ping: 1 })' | mongosh --quiet --username mongo --password root --authenticationDatabase admin localhost:27017/db_badge"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Wait for MongoDB to be ready
        run: |
          echo "Waiting for MongoDB..."
          for i in {1..10}; do
            if echo 'db.runCommand({ ping: 1 })' | mongosh --quiet --username mongo --password root --authenticationDatabase admin localhost:27017/db_badge; then
              echo "MongoDB is ready"
              break
            fi
            sleep 5
          done

      - name: Run Maven tests
        env:
          SPRING_DATA_MONGODB_HOST: localhost
          SPRING_DATA_MONGODB_PORT: 27017
          SPRING_DATA_MONGODB_DATABASE: db_badge
          SPRING_DATA_MONGODB_USERNAME: mongo
          SPRING_DATA_MONGODB_PASSWORD: root
          SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE: admin
        run: mvn test
